[package]
name = "tauri-plugin-jarvis"
version = "0.0.0"
authors = ["You"]
description = ""
edition = "2021"
rust-version = "1.70"
exclude = ["/examples", "/webview-dist", "/webview-src", "/node_modules"]
links = "tauri-plugin-jarvis"

[dependencies]
tauri = { version = "2.0.0-beta" }
serde = "1.0"
thiserror = "1.0"
applications = { path = "../../vendors/applications-rs" }
# applications = { version = "0.2.1-alpha.2" }
anyhow = "1.0.86"
tar = "0.4.40"
flate2 = "1.0.30"
tauri-icns = "0.1.0"
serde_json = "1.0.117"
window-vibrancy = "0.5.0"
tauri-plugin-store = "2.0.0-beta"
axum = { version = "0.6.20" }
axum-extra = { version = "0.8.0" }
tower = { version = "0.4", features = ["util"] }
tower-http = { version = "0.4.0", features = ["fs", "trace"] }
tonic = "0.11"
tonic-reflection = "0.11.0"
uuid = { version = "1.8.0", features = ["v4"] }


[build-dependencies]
tauri-plugin = { version = "2.0.0-beta", features = ["build"] }
tonic-build = "0.11"
